### ISSUE TITLE
Running a bot from within a Docker container makes it not work

### ISSUE THREAD

**Issue by SamusAranX** [bwmarrin/discordgo#1365]
I'm kind of at a loss with this one because, to be honest, I don't know all that much about Docker.

Here's the Dockerfile I wrote for my bot:

```dockerfile
ARG GOLANG_VERSION=1-alpine
ARG ALPINE_VERSION=latest

FROM golang:${GOLANG_VERSION} AS discordbot-builder
RUN apk update && apk --no-cache add make git tzdata
ENV TZ=Europe/Berlin
WORKDIR /discordbot/
COPY . .
RUN go get
RUN make build

FROM alpine:${ALPINE_VERSION} AS discordbot-runner
VOLUME /data
RUN apk update && apk --no-cache add tzdata imagemagick
ENV TZ=Europe/Berlin
WORKDIR /discordbot/
COPY --from=discordbot-builder /discordbot/discordbot /bin/discordbot
ENTRYPOINT ["discordbot"]
```

I wrote a docker-compose.yml to go with it:

```yml
services:
  discordbot:
    image: discordbot
    container_name: discordbot
    restart: on-failure
    env_file: .env
    volumes:
      - ./data:/data # make sure the bot can find its data
```

If I start the bot using `docker compose` while keeping an eye on the logs, it appears to start normally.
It connects to Discord, registers a bunch of commands, and then starts idling. 
The problem is that it never appears as online in the servers it's on and it doesn't react to interactions like slash commands.
I ran the bot outside of a container and it worked normally.
Has anyone encountered an issue like this before? If so, how did you fix it?
