### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by SynergyBest** [bwmarrin/discordgo#898]
The website (http://bwmarrin.github.io/discordgo/ ) 404’s

**Comment by KAIYOHUGO** [comment]
i find that the site is build by using  [mkdocs](https://www.mkdocs.org/)
and some files are missing (./site/*)

and this is the config file
```yaml
site_name: DiscordGo
site_author: Bruce Marriner
site_url: http://bwmarrin.github.io/discordgo/
repo_url: https://github.com/bwmarrin/discordgo

dev_addr: 0.0.0.0:8000
theme: yeti

markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists

pages:
    - 'Home': 'index.md'
    - 'Getting Started': 'GettingStarted.md'
```

but it's seem like the site has been deleted long time ago🤔
